version: "3.9"
services:
  expressapp:
    container_name: expressapp
    build: ./backend
    expose:
      - 8000
    ports:
      - 8000:4000
    volumes:
      - ./backend:/usr/src/app
  reactapp:
    stdin_open: true
    container_name: reactapp
    build: ./frontend
    expose:
      - 8080
    ports:
        - 8080:80
    environment:
          - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/usr/src/app
    links:
      - expressapp



  