version: "3.9"
services:
  expressapp:
    container_name: expressapp
    build: ./backend
    expose:
      - 8000
    volumes:
      - ./backend:/usr/src/app
  reactapp:
    container_name: reactapp
    build: ./frontend
    expose:
      - 5000
    volumes:
      - ./frontend:/usr/src/app
  nginx:
    build: ./nginx
    expose:
      - 80
    links:
      - expressapp
      - reactapp
    restart: always


  